version: '3.8'

services:
  db-service:
    image: postgres:13.8-alpine
    container_name: "architecture-db"
    restart: always
    environment:
      - POSTGRES_DB=db01
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123
    ports:
      - 5432:5432
