server:
  port: 9099

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/architecture-db
    username: postgres
    password: qwerty123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc.time_zone: UTC
  flyway:
    enabled: true


springdoc:
  swagger-ui:
    path: "/swagger"
    disable-swagger-default-url: true
    use-root-path: true